name: minerva_controller_annotation
description: A sample command-line application.
version: 0.9.0
homepage: https://github.com/GlebBatykov/minerva_controller_annotation

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  minerva: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
